---
version: "3.3"
services:
  frontend:
    container_name: animalwiki-frontend
    image: animalwiki/frontend
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: animalwiki-frontend
    ports:
      - "3000:3000"
    networks:
      - animalwiki
    restart: unless-stopped
  
  backend:
    container_name: animalwiki-backend
    image: animalwiki/backend
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: animalwiki-backend
    ports:
      - "8080:8080"
    networks:
      - animalwiki
    restart: unless-stopped

  redis:
    container_name: animalwiki-redis
    image: redis:alpine
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - animalwiki-data:/data
    command: ["redis-server", "/etc/redis/redis.conf", "--loglevel warning", "--appendonly yes"]
    ports:
      - "6379:6379"
    networks:
      - animalwiki
    restart: unless-stopped

volumes:
  animalwiki-data:
    name: animalwiki-data
networks:
  animalwiki:
    name: animalwiki